/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillboardControlPanel.view;

import javax.swing.*;
import java.awt.*;

/**
 * Error Page
 * @author Asus
 */
public class ErrorPage extends javax.swing.JFrame {
    /**
     * Creates new form ErrorPage
     */
    public ErrorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        errorPanel = new javax.swing.JPanel();
        lbThirdLine = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();
        lbAppName = new javax.swing.JLabel();
        lbSecondLine = new javax.swing.JLabel();
        lbFirstLine = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        errorPanel.setBackground(new java.awt.Color(255, 255, 255));
        errorPanel.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        errorPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        errorPanel.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());

        lbThirdLine.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lbThirdLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThirdLine.setText("Please check the ServerConnection with the server and re-open the app");

        lbClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbClose.setForeground(new java.awt.Color(54, 33, 89));
        lbClose.setText("X");
        lbClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCloseMousePressed(evt);
            }
        });

        lbAppName.setFont(new java.awt.Font("MV Boli", 0, 60)); // NOI18N
        lbAppName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAppName.setText("BBCreator");

        lbSecondLine.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lbSecondLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSecondLine.setText("Something went wrong with the server");

        lbFirstLine.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lbFirstLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFirstLine.setText("The app couldn't load");

        lbBackground.setBackground(new java.awt.Color(245, 245, 245));
        lbBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbBackground.setForeground(new java.awt.Color(255, 255, 255));
        lbBackground.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/bg_log_in.png")); // NOI18N
        lbBackground.setPreferredSize(new java.awt.Dimension(1920, 1080));
        lbBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbBackgroundMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout errorPanelLayout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(errorPanelLayout);
        errorPanelLayout.setHorizontalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(lbSecondLine, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(lbThirdLine, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(1880, 1880, 1880)
                .addComponent(lbClose))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(lbAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(lbFirstLine, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        errorPanelLayout.setVerticalGroup(
            errorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(lbSecondLine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbThirdLine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbClose))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lbAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(errorPanelLayout.createSequentialGroup()
                .addGap(530, 530, 530)
                .addComponent(lbFirstLine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(errorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbCloseMousePressed

    private void lbBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackgroundMouseDragged

    }//GEN-LAST:event_lbBackgroundMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel lbAppName;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbFirstLine;
    private javax.swing.JLabel lbSecondLine;
    private javax.swing.JLabel lbThirdLine;
    // End of variables declaration//GEN-END:variables
}
