package BillboardControlPanel.view;


import ServerConnection.Exceptions.ServerClosedException;
import ServerConnection.ServerConnection;
import Commmunication.Requests.LogoutRequest;
import Utils.Token.Token;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Home Page
 * @author Asus
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private String token;
    private String permission;
    private String currentUser;
    private String userId;
    private Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    public Home(String token) {
        this.token = token;
        String decodedToken = Token.decodeToken(this.token);
        //Get user information from decoded token
        this.permission = decodedToken.split("%%%%")[2];
        this.currentUser = decodedToken.split("%%%%")[1];
        this.userId = decodedToken.split("%%%%")[0];

        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        lbIconHome = new javax.swing.JLabel();
        lbHome = new javax.swing.JLabel();
        btnCreate = new javax.swing.JPanel();
        lbIconCreate = new javax.swing.JLabel();
        lbCreate = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        btnList = new javax.swing.JPanel();
        lbIconList = new javax.swing.JLabel();
        lb_list_billboards = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        lbIconEdit = new javax.swing.JLabel();
        lbEdit = new javax.swing.JLabel();
        btnSchedule = new javax.swing.JPanel();
        lbIconSchedule = new javax.swing.JLabel();
        lbSchedule = new javax.swing.JLabel();
        lbAppNameLeft = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JPanel();
        lbIconLogout = new javax.swing.JLabel();
        lbLogout = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        lbWelcomeTitle = new javax.swing.JLabel();
        lbWelcomeInfo = new javax.swing.JLabel();
        lbClose = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        lbAppName = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        btGetStarted = new javax.swing.JButton();
        lbIconCup = new javax.swing.JLabel();
        lbIconGirl = new javax.swing.JLabel();
        lbIconLaptop = new javax.swing.JLabel();
        lbIconShoes = new javax.swing.JLabel();
        lbUserInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        homePanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        homePanel.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        homePanel.setLayout(null);

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setPreferredSize(new Dimension(screenSize.width / 5, screenSize.height));
        sidepanel.setLayout(null);

        btnHome.setBackground(new java.awt.Color(85, 65, 118));
        btnHome.setPreferredSize(new Dimension(screenSize.width / 5, 50) );

        lbIconHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconHome.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_home_15px_1.png")); // NOI18N
        lbIconHome.setToolTipText("");

        lbHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbHome.setForeground(new java.awt.Color(204, 204, 204));
        lbHome.setText("Home");

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHome)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbHome)
                    .addComponent(lbIconHome, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btnHome);
        btnHome.setBounds(0, 190, 384, 50);

        btnCreate.setBackground(new java.awt.Color(64, 43, 100));
        btnCreate.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCreateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCreateMousePressed(evt);
            }
        });

        lbIconCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconCreate.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_create_15px.png")); // NOI18N
        lbIconCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCreateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCreateMousePressed(evt);
            }
        });

        lbCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCreate.setForeground(new java.awt.Color(204, 204, 204));
        lbCreate.setText("Create Billboards");
        lbCreate.setToolTipText("");
        lbCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCreateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCreateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCreateMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCreateLayout = new javax.swing.GroupLayout(btnCreate);
        btnCreate.setLayout(btnCreateLayout);
        btnCreateLayout.setHorizontalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCreateLayout.setVerticalGroup(
            btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIconCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lbCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        sidepanel.add(btnCreate);
        btnCreate.setBounds(0, 240, 384, 50);

        separator.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepanel.add(separator);
        separator.setBounds(30, 90, 220, 10);

        btnList.setBackground(new java.awt.Color(64, 43, 100));
        btnList.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btnList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconListMousePressed(evt);
            }
        });

        lbIconList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconList.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_list_15px.png")); // NOI18N
        lbIconList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconListMousePressed(evt);
            }
        });

        lb_list_billboards.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_list_billboards.setForeground(new java.awt.Color(204, 204, 204));
        lb_list_billboards.setText("List Billboards");
        lb_list_billboards.setToolTipText("");
        lb_list_billboards.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconListMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnListLayout = new javax.swing.GroupLayout(btnList);
        btnList.setLayout(btnListLayout);
        btnListLayout.setHorizontalGroup(
            btnListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_list_billboards)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        btnListLayout.setVerticalGroup(
            btnListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_list_billboards, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(lbIconList, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnList);
        btnList.setBounds(0, 290, 384, 50);

        btnEdit.setBackground(new java.awt.Color(64, 43, 100));
        btnEdit.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbEditMousePressed(evt);
            }
        });

        lbIconEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconEdit.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_edit_profile_15px_1.png")); // NOI18N
        lbIconEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbEditMousePressed(evt);
            }
        });

        lbEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbEdit.setForeground(new java.awt.Color(204, 204, 204));
        lbEdit.setText("Edit Users");
        lbEdit.setToolTipText("");
        lbEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbEditMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEdit)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnEdit);
        btnEdit.setBounds(0, 390, 384, 50);

        btnSchedule.setBackground(new java.awt.Color(64, 43, 100));
        btnSchedule.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btnSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconScheduleMousePressed(evt);
            }
        });

        lbIconSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconSchedule.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_schedule_15px_1.png")); // NOI18N
        lbIconSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconScheduleMousePressed(evt);
            }
        });

        lbSchedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSchedule.setForeground(new java.awt.Color(204, 204, 204));
        lbSchedule.setText("Schedule Billboards");
        lbSchedule.setToolTipText("");
        lbSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbIconScheduleMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbIconScheduleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnScheduleLayout = new javax.swing.GroupLayout(btnSchedule);
        btnSchedule.setLayout(btnScheduleLayout);
        btnScheduleLayout.setHorizontalGroup(
            btnScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnScheduleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSchedule)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        btnScheduleLayout.setVerticalGroup(
            btnScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lbIconSchedule, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepanel.add(btnSchedule);
        btnSchedule.setBounds(0, 340, 384, 50);

        lbAppNameLeft.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbAppNameLeft.setForeground(new java.awt.Color(204, 204, 204));
        lbAppNameLeft.setText("BBCreator");
        sidepanel.add(lbAppNameLeft);
        lbAppNameLeft.setBounds(30, 50, 115, 32);

        btnLogOut.setBackground(new java.awt.Color(64, 43, 100));
        btnLogOut.setPreferredSize(new Dimension(screenSize.width / 5, 50 ));
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        lbIconLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIconLogout.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_logout_rounded_left_15px.png")); // NOI18N
        lbIconLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        lbLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLogout.setForeground(new java.awt.Color(204, 204, 204));
        lbLogout.setText("Log Out");
        lbLogout.setToolTipText("");
        lbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLogoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnLogOutLayout = new javax.swing.GroupLayout(btnLogOut);
        btnLogOut.setLayout(btnLogOutLayout);
        btnLogOutLayout.setHorizontalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLogOutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbIconLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLogout)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        btnLogOutLayout.setVerticalGroup(
            btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(btnLogOut);
        btnLogOut.setBounds(0, 950, 384, 60);

        homePanel.add(sidepanel);
        sidepanel.setBounds(0, 0, 384, 1080);

        welcomePanel.setBackground(new java.awt.Color(110, 89, 222));
        welcomePanel.setPreferredSize(new Dimension(screenSize.width / 5 * 4, 150 ));

        lbWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbWelcomeTitle.setForeground(new java.awt.Color(204, 204, 204));
        lbWelcomeTitle.setText("Welcome to BBCreator !");

        lbWelcomeInfo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbWelcomeInfo.setForeground(new java.awt.Color(204, 204, 204));
        lbWelcomeInfo.setText("Start building your own billboard and share it with your friends.");
        lbWelcomeInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbWelcomeInfo)
                    .addComponent(lbWelcomeTitle))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbWelcomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbWelcomeInfo)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        homePanel.add(welcomePanel);
        welcomePanel.setBounds(380, 90, 1610, 150);

        lbClose.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbClose.setForeground(new java.awt.Color(54, 33, 89));
        lbClose.setText("X");
        lbClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbCloseMousePressed(evt);
            }
        });
        homePanel.add(lbClose);
        lbClose.setBounds(1880, 10, 16, 32);

        lbDescription.setBackground(new java.awt.Color(51, 51, 51));
        lbDescription.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbDescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDescription.setText("<html>Create stunning billboards<br>and earn the bragging rights<br>with your friends.");
        lbDescription.setToolTipText("");
        lbDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        homePanel.add(lbDescription);
        lbDescription.setBounds(460, 490, 760, 220);

        lbAppName.setBackground(new java.awt.Color(51, 51, 51));
        lbAppName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbAppName.setText("We ♥ BBCreator");
        homePanel.add(lbAppName);
        lbAppName.setBounds(470, 20, 137, 25);

        lbTitle.setBackground(new java.awt.Color(51, 51, 51));
        lbTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbTitle.setText("THE #1 BILLBOARD GENERATOR  ");
        homePanel.add(lbTitle);
        lbTitle.setBounds(460, 450, 302, 22);

        btGetStarted.setBackground(new java.awt.Color(110, 89, 222));
        btGetStarted.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btGetStarted.setForeground(new java.awt.Color(255, 255, 255));
        btGetStarted.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/icons8_hand_right_18px.png")); // NOI18N
        btGetStarted.setText("See all billboards");
        btGetStarted.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btGetStarted.setBorderPainted(false);
        btGetStarted.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btGetStarted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGetStartedActionPerformed(evt);
            }
        });
        homePanel.add(btGetStarted);
        btGetStarted.setBounds(460, 690, 250, 60);

        lbIconCup.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/hp-hero-mug-hover.jpg")); // NOI18N
        homePanel.add(lbIconCup);
        lbIconCup.setBounds(1080, 540, 200, 200);

        lbIconGirl.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/hp-hero-tshirt-hover.jpg")); // NOI18N
        homePanel.add(lbIconGirl);
        lbIconGirl.setBounds(990, 750, 400, 274);

        lbIconLaptop.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/hp-hero-laptop-hover.jpg")); // NOI18N
        homePanel.add(lbIconLaptop);
        lbIconLaptop.setBounds(1310, 280, 500, 340);

        lbIconShoes.setIcon(new javax.swing.ImageIcon("src/main/java/BillboardControlPanel/view/images/hp-hero-magazine-hover.jpg")); // NOI18N
        homePanel.add(lbIconShoes);
        lbIconShoes.setBounds(1470, 670, 400, 273);

        lbUserInfo.setBackground(new java.awt.Color(51, 51, 51));
        lbUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbUserInfo.setText("Username: " + currentUser + "  ID: " + userId );
        homePanel.add(lbUserInfo);
        lbUserInfo.setBounds(1600, 15, 220, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lbCloseMousePressed

    private void lbCreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCreateMouseEntered
        btnCreate.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lbCreateMouseEntered

    private void lbCreateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCreateMouseExited
        btnCreate.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lbCreateMouseExited

    private void lbCreateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCreateMousePressed
        // Access Create Billboards Page if users have "CB" permission
        if (this.permission.contains("CB")) {
            CreateBillboardsPage createBillboardsPage = new CreateBillboardsPage(token);
            createBillboardsPage.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(homePanel, "Do not have permission");
        }
    }//GEN-LAST:event_lbCreateMousePressed

    private void lbIconListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconListMouseEntered
        btnList.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lbIconListMouseEntered

    private void lbIconListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconListMouseExited
        btnList.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lbIconListMouseExited

    private void lbIconListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconListMousePressed
        ListBillboardsPage listBillboardsPage = new ListBillboardsPage(token);
        listBillboardsPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbIconListMousePressed

    private void lbIconScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconScheduleMouseEntered
        btnSchedule.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lbIconScheduleMouseEntered

    private void lbIconScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconScheduleMouseExited
        btnSchedule.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lbIconScheduleMouseExited

    private void lbIconScheduleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbIconScheduleMousePressed
        // Access Create Billboards Page if users have "CB" permission
        if (this.permission.contains("SB")) {
            ScheduleBillboardsPage scheduleBillboardsPage = new ScheduleBillboardsPage(token);
            scheduleBillboardsPage.setVisible(true);
            this.setVisible(false);
        }
        else {
            JOptionPane.showMessageDialog(homePanel, "Do not have permission");
        }
    }//GEN-LAST:event_lbIconScheduleMousePressed

    private void lbEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEditMouseEntered
        btnEdit.setBackground(new java.awt.Color(85,65,118));
    }//GEN-LAST:event_lbEditMouseEntered

    private void lbEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEditMouseExited
        btnEdit.setBackground(new java.awt.Color(64, 43, 100));
    }//GEN-LAST:event_lbEditMouseExited

    private void lbEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbEditMousePressed
        EditUserPage editUserPage = new EditUserPage(token);
        editUserPage.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_lbEditMousePressed

    private void btGetStartedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGetStartedActionPerformed
        ListBillboardsPage listBillboardsPage = new ListBillboardsPage(token);
        listBillboardsPage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btGetStartedActionPerformed

    private void lbLogoutMousePressed(java.awt.event.MouseEvent evt){//GEN-FIRST:event_lbLogoutMousePressed
        // Log out
        try{
            // Connect to server to send log out request
            ServerConnection svCon = new ServerConnection();
            svCon.sendRequest(new LogoutRequest());
            new LogIn().setVisible(true);
            this.dispose();
        } catch (ServerClosedException e) {
            JOptionPane.showMessageDialog(homePanel, e.getMessage());
            System.exit(0);
        }


    }//GEN-LAST:event_lbLogoutMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGetStarted;
    private javax.swing.JPanel btnCreate;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnList;
    private javax.swing.JPanel btnLogOut;
    private javax.swing.JPanel btnSchedule;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel lbAppName;
    private javax.swing.JLabel lbAppNameLeft;
    private javax.swing.JLabel lbClose;
    private javax.swing.JLabel lbCreate;
    private javax.swing.JLabel lbDescription;
    private javax.swing.JLabel lbEdit;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbIconCreate;
    private javax.swing.JLabel lbIconCup;
    private javax.swing.JLabel lbIconEdit;
    private javax.swing.JLabel lbIconGirl;
    private javax.swing.JLabel lbIconHome;
    private javax.swing.JLabel lbIconLaptop;
    private javax.swing.JLabel lbIconList;
    private javax.swing.JLabel lbIconLogout;
    private javax.swing.JLabel lbIconSchedule;
    private javax.swing.JLabel lbIconShoes;
    private javax.swing.JLabel lbLogout;
    private javax.swing.JLabel lbSchedule;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUserInfo;
    private javax.swing.JLabel lbWelcomeInfo;
    private javax.swing.JLabel lbWelcomeTitle;
    private javax.swing.JLabel lb_list_billboards;
    private javax.swing.JSeparator separator;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
